### PR TITLE
Use a hash table for duplication detection

### PR DESCRIPTION
**Pull request by dajva**
This gives a significant speed up on larger projects (ten thousands of
files).

### CODE REVIEW

**Comment by redguardtoo** [comment]
check #11 , I will check what I can learn from helm-ls-git-ls

**Comment by dajva** [comment]
Out of interest, what are your plans for duplication separation?
I really need to avoid using full path mode since it is too slow, at least with ido.
I think using parts of the path is reasonable, maybe just extend with another level in the path until it's unique would be enough?

**Comment by redguardtoo** [comment]
`(setq ido-enable-flex-matching t)`

**Comment by redguardtoo** [comment]
what do you mean slow? you need type too many characters to locate a file? send me the file if possible.

**Comment by dajva** [comment]
Slow, as in ido get stalled after a key stroke to wait for the filtering to happen.
Try using ffip on a project with 50.000+ number of files with full path.

**Comment by dajva** [comment]
The usability also suffers for large projects where you will naturally have long paths that might interfere with what you are trying to match, i.e. more key strokes to find the file you need and possibly also some manual selecting after that.

Anyway, I was asking mostly out of interest. I have my own patches to make it work reasonably on large projects so I am curious in which direction this project is moving and if it is any idea for me to rebase my stuff and possibly create some more pull requests.

Maybe your focus is more on smaller projects.

**Comment by redguardtoo** [comment]
I plan to make it support big projects. Could you send me the patches?

I use full path by default because we often use part of path to locate file in real project. Similar file names are harder to type.

about performance issue of ido, do GC optimization helps? see the last section of https://github.com/lewang/flx

**Comment by dajva** [comment]
I will see if I can rebase my patches on top of the new additions you made without too much hassle. Since I did not get any response on this pull req I've been diverging a bit also from the base version which I think was 3.2. IIRC the main optimization was caching but it was some time since I looked at it so don't remember the details right now.

Thanks for the tip about gc threshold. I'll see if that improve things.

**Comment by redguardtoo** [comment]
cool. .

**Pull request closed without merging**
