### PR TITLE
add fd command

### PR DESCRIPTION
**Pull request by xianghx**
I am not very sure.  I am not good at elisp. so I try it . Hope it work.

### CODE REVIEW

**Comment by redguardtoo** [comment]
Could you use only `ffip-prune-patterns`? Or else this package is too bloated for average users. You can use `-E` from `fd`.

Please squash with your previous commit and `git push -f`.

**Comment by xianghx** [comment]
ffip-prune-patterns doesn't work. \ */node_modules/\*   前面多了一个星号。
我用中文了， 下面是我的一些想法：
1.  ffip-fd-prune-patterns is empty
fd 使用的 .gitignore文件。 当不在gitignore里面时，ffip-fd-prune-patterns 可以起到补充的作用，。

2. 不要手动管理
the best way：
(setq  ffip-fd-options . " --ignore-file <path>...'")
最好的方式是把需要的全部放到.gitignore文件。可以起个名字叫 fd.gitignore 放到emacs 配置里。

使用 joe 
$ go get -u github.com/karan/joe
$ joe u
$ joe g java    # outputs .gitignore file for java to stdout
$ joe g java > .gitignore    # saves a new .gitignore file for java
$ joe g java >> .gitignore    # appends to an existing .gitignore file
$ joe g java,node,osx > .gitignore    # saves a new .gitignore file for multiple languages

**Comment by xianghx** [comment]
ffip-prune-patterns ?  I don't know how to fix it?

whitespace is  ok.

**Comment by xianghx** [comment]
maybe have some problem. I close it, redo

**Pull request closed without merging**
